const fs = require('fs');
const contentMG = fs.readFileSync('js/math-galaxy.js', 'utf8');
const cadetStr = contentMG.match(/function genCadet[\s\S]*?const types = \[(.*?)\];/)[1].replace(/'/g, '').replace(/ /g, '').split(',');
const expStr = contentMG.match(/function genExplorer[\s\S]*?const types = \[(.*?)\];/)[1].replace(/'/g, '').replace(/ /g, '').split(',');
const pilotStr = contentMG.match(/function genPilot[\s\S]*?const types = \[(.*?)\];/)[1].replace(/'/g, '').replace(/ /g, '').split(',');
const comStr = contentMG.match(/function genCommander[\s\S]*?const types = \[(.*?)\];/)[1].replace(/'/g, '').replace(/ /g, '').split(',');
console.log("Cadet types:", cadetStr);
console.log("Explorer types:", expStr);
console.log("Pilot types:", pilotStr);
console.log("Commander types:", comStr);
